### ISSUE TITLE
Bug in SSE2NEON.h

### ISSUE THREAD

**Issue by tdao006** [jratcliff63367/sse2neon#1]
Hello,

Thank you for sharing your source code.

There is a bug in file SSE2NEON.h, line 361 in function 

template <int i > FORCE_INLINE __m128 _mm_shuffle_ps_function(__m128 a, __m128 b)

Current code:
default: _mm_shuffle_ps_default<i>(a, b);

The correct code should be:
default: _return_ _mm_shuffle_ps_default<i>(a, b);

Thank you,
Tuan Dao.

**Comment by jratcliff63367** [comment]
Hopefully this is fixed by now.
