### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by danthony06** [jratcliff63367/sse2neon#18]
There is no license file in the repository, and I didn't see any mentioned in the source. Is there a particular license this is supposed to be released under?

**Comment by nemequ** [comment]
It's MIT.  The license is in [SSE2NEON](https://github.com/jratcliff63367/sse2neon/blob/6eba2f9097e2de44052462cd78cdb05ba2bf8000/SSE2NEON.h#L89).

**Comment by jserv** [comment]
Clarify in [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon), MIT License.
