### ISSUE TITLE
Use __GNUC__ instead of GCC

### ISSUE THREAD

**Issue by weitjong** [jratcliff63367/sse2neon#3]
Instead of defining `GCC` manually and using it in `#if GCC`, replace all the `#if GCC` with `#ifdef __GNUC__`. The latter is defined for all the GCC-derived or GCC-compatible compilers (including Android NDK and Clang).

**Comment by jratcliff63367** [comment]
Hopefully this has been fixed with the latest version.

**Comment by weitjong** [comment]
Sorry for late reply. I think we can close this.
