### ISSUE TITLE
How to convert _mm_madd_epi16 to neon instructions

### ISSUE THREAD

**Issue by zhangfrank** [jratcliff63367/sse2neon#5]
Hi,
Thank you for your work to convert SSE instructions to NEON! Do you know how to convert _mm_madd_epi16 to neon instructions? Many thanks!

Best Regards,

Frank

**Comment by jratcliff63367** [comment]
No, that one hasn't been implemented yet.  I'll add it to my todo list.

**Comment by zhangfrank** [comment]
Good, thank you!
Frank

**Comment by nemequ** [comment]
```c
  int32x4_t pl = vmull_s16(vget_low_s16(a),  vget_low_s16(b));
  int32x4_t ph = vmull_s16(vget_high_s16(a), vget_high_s16(b));
  int32x2_t rl = vpadd_s32(vget_low_s32(pl), vget_high_s32(pl));
  int32x2_t rh = vpadd_s32(vget_low_s32(ph), vget_high_s32(ph));
  int32x4_t result = vcombine_s32(rl, rh);
```

AArch64 would make things a bit easier, I think.

**Comment by jserv** [comment]
Implemented in [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon).
