### ISSUE TITLE
Add new functions for librealsense 

### ISSUE THREAD

**Issue by ZahraBoroujeni** [jratcliff63367/sse2neon#6]
Hi All,

I want to use the Intel camera sr300 in Odroidxu4, therefore I need to convert some functions from SSE to NEON, which are at least four functions:
- _mm_setr_epi8
- _mm_shuffle_epi8
- _mm_storeu_si128
- _mm_alignr_epi8

I would be appreciated for any help.
[Librealsense code](https://github.com/IntelRealSense/librealsense/blob/master/src/image.cpp)
Best

**Comment by jratcliff63367** [comment]
Yeah, these haven't been done yet.  I'll at least add them to my TODO list.

**Comment by jserv** [comment]
Implemented in [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon).
